### ISSUE TITLE
Keep recieving uncaught type error

### ISSUE THREAD

**Issue by Not-Mark** [mattser/not-tetris#10]
Hello,

I have tried to play your game but I keep seeing an "uncaught type" error everytime I press the left button.

Please fix as this is unacceptable

**Comment by lucas-s-work** [comment]
Yer im having the same issue when I open the js source and edit it, pls fix thanks

**Comment by Not-Mark** [comment]
@lucas-s-work  How have you managed to do this? I cannot get this to compile using the Csharp Library?

**Comment by lucas-s-work** [comment]
Sorry I cannot help as this was ran on an reverse nginx proxy that automatically fondles the sauce code. If you are still getting uncaught type checking then I suggest turning off type checking in javascript. I hope this helps :)

**Comment by Not-Mark** [comment]
Never mind figured it out, thanks for the help

**Comment by lucas-s-work** [comment]
good.

**Comment by mattser** [comment]
Have you tried turning it off and on again?
