### ISSUE TITLE
[HELP] I keep losing 

### ISSUE THREAD

**Issue by lucas-s-work** [mattser/not-tetris#9]
:shipit:

**Comment by lucas-s-work** [comment]
I keep reaching the top of the screen for some reason which means I lose :( can you add an exception for my ip pls, it's 192.168.0.0.1 ty :)

**Comment by Not-Mark** [comment]
@lucas-s-work have you considered getting good?

**Comment by mattser** [comment]
Have you tried turning it off and on again?

**Comment by lucas-s-work** [comment]
Thank u, that resolved the issue
